name: Jacob Proffer
title: Jacob Proffer
url: http://jacobproffer.com
baseurl: /
description: Jacob Proffer is a designer &amp; developer working at Elegant Seagulls in Marquette, Michigan.
exclude:
  - assets/
  - gulp/package.json
  - gulp/node_modules
  - gulp/gulpfile.js
