name: Jacob Proffer
title: Jacob Proffer
url: http://jacobproffer.com
baseurl: /
description: Jacob Proffer is a Front-End Developer working at Elegant Seagulls in Marquette, Michigan.
permalink: /:categories/:title/
exclude:
  - assets/
  - gulp/package.json
  - gulp/node_modules
  - gulp/gulpfile.js
