baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "jacobproffer"
paginate = 8
paginatePath = "posts"
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Travel and language study blog of Jacob Proffer."
  subTitle = "Front-End Developer and Traveler"
  images = ["images/jacobproffer-social.jpg"]

[menu]

  [[menu.main]]
    identifier = "series"
    name = "Series"
    pageRef = "/series/"
    weight = 1

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/jacobproffer"
    weight = 1

  [[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/jacobproffer_/"
    weight = 2

  [[menu.social]]
    identifier = "repository"
    name = "Repository"
    url = "https://github.com/jacobproffer/blog"
    weight = 3
