baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "jacobproffer"
paginate = 12
paginatePath = "posts"
copyright = "2024"
timeout = 60000
ignoreErrors = ["error-disable-taxonomy"]

[imaging]
  anchor = "Smart"
  bgColor = "#ff683f"
  hint = "photo"
  quality = 100
  resampleFilter = "Lanczos"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Travel and language study blog of Jacob Proffer."
  images = ["images/jacobproffer-social.jpg"]

[menu]

  [[menu.main]]
    identifier = "japanese"
    name = "Japanese"
    pageRef = "/japanese/"
    weight = 1

  [[menu.main]]
    identifier = "travel"
    name = "Travel"
    pageRef = "/travel/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    pageRef = "/contact/"
    weight = 3

  [[menu.internal]]
    identifier = "tags"
    name = "Tags"
    pageRef = "/tags/"

  [[menu.internal]]
    identifier = "categories"
    name = "Categories"
    pageRef = "/categories/"

  [[menu.internal]]
    identifier = "series"
    name = "Series"
    pageRef = "/series/"

  [[menu.social]]
    identifier = "dribbble"
    name = "Dribbble"
    url = "https://dribbble.com/jacobproffer/"

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/jacobproffer/"

  [[menu.social]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "https://proffer.dev/"
