baseURL = "http://jacobproffer.com/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "jacobproffer"
publishDir = "docs"
paginate = 8
paginatePath = "posts"

[params]
  description = "Jacob Proffer is a Front-End Developer working at Elegant Seagulls in Marquette, Michigan."
  socialImage = "/images/jacobproffer-social.jpg"