baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "jacobproffer"
paginate = 8
paginatePath = "posts"
copyright = "2023"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Travel and language study blog of Jacob Proffer."
  images = ["images/jacobproffer-social.jpg"]

[menu]

  [[menu.main]]
    identifier = "japanese"
    name = "Japanese"
    pageRef = "/japanese/"

  [[menu.main]]
    identifier = "travel"
    name = "Travel"
    pageRef = "/travel/"

  [[menu.social]]
    identifier = "dribbble"
    name = "Dribbble"
    url = "https://dribbble.com/jacobproffer/"

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/jacobproffer/"

  [[menu.social]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "https://proffer.dev/"
