baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "jacobproffer"
paginate = 8
paginatePath = "posts"
googleAnalytics = "UA-57480521-1"
enableRobotsTXT = true
summaryLength = 14

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Travel and language study blog of Jacob Proffer."
  subTitle = "Front-End Developer and Traveler"
  socialImage = "images/jacobproffer-social.jpg"

[menu]

  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile/"
    weight = 1

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/jacobproffer"
    weight = 1