baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "jacobproffer"
publishDir = "docs"
paginate = 8
paginatePath = "posts"
googleAnalytics = "UA-57480521-1"
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Jacob Proffer is a Front-End Developer working at Elegant Seagulls in Marquette, Michigan."
  subTitle = "Front-End Developer"
  socialImage = "images/jacobproffer-social.jpg"

[menu]

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/jacobproffer"
    weight = 1

  [[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/jacobproffer_/"
    weight = 2