name = "Jacob Proffer"
description = "This is the source code for Jacob Proffer's Blog."
homepage = "http://jacobproffer.com/"
tags = ["blog"]
features = ["blog", "posts"]
min_version = "0.41"

[author]
  name = "Jacob Proffer"
  homepage = "http://proffer.dev/"
