name = "Jacob Proffer"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "This is the source code for Jacob Proffer's Blog."
homepage = "http://jacobproffer.com/"
tags = ["blog"]
features = []
min_version = "0.41"

[author]
  name = "Jacob Proffer"
  homepage = "http://jacobproffer.com"
