backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
collections:
  - name: "general"
    label: "General"
    folder: "content/general"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Images", name: "images", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "travel"
    label: "Travel"
    folder: "content/travel"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Images", name: "images", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Series", name: "series", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "education"
    label: "Education"
    folder: "content/education"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Images", name: "images", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Series", name: "series", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}